// 1. using rest operator function concept pass n no of arguments and get the maxium of it (forEach)
// 2.using rest operator function concept pass n no of arguments and get the minimum of it (reduce)
// 3.using rest operator function concept pass n no of arguments and get the sum of even numbers of it (forEach)
// 4.using rest operator function concept pass n no of arguments and  get the sum of even numbers of it(reduce)
// 5.using rest operator function concept pass n no of arguments an get the sum of all prime numbers of it(reduce)
// 6.5.using rest operator function concept pass n no of character arguments an get the count of all vowels numbers of it.(forEach)